/*
tiktok shop openapi

Testing AnalyticsV202406APIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sdk_golang

import (
	"context"
	openapiclient "github.com/Jaya-Pratama-Teknik-Group/tts-go-sdk/apis"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_sdk_golang_AnalyticsV202406APIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AnalyticsV202406APIService Analytics202406ShopSkusPerformanceGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.AnalyticsV202406API.Analytics202406ShopSkusPerformanceGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AnalyticsV202406APIService Analytics202406ShopSkusSkuIdPerformanceGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var skuId string

		resp, httpRes, err := apiClient.AnalyticsV202406API.Analytics202406ShopSkusSkuIdPerformanceGet(context.Background(), skuId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
